---
title: "Homework 5"
author: "Holly Finertie"
date: "11/5/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1

```{r}
library(tidyverse)
library(rvest)
library(readr)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```


```{r}
update_missing = function(x) {
  
  if(is.numeric(x)) {
    replace(x, is.na(x), round(mean(x, na.rm = TRUE), digits = 1))
  }
  
  else if(!is.numeric(x)) {
    replace(x, is.na(x),"virginica")
  }
}

iris_no_missing = map_df(iris_with_missing, ~update_missing(.x))
```

## Problem 2

```{r}
read_file = function(x) {
  
  y = read_csv(x)
  
}

source_df = tibble(
   file = list.files(path = "./data/"), 
   path = str_c("./data/", file))

longitudinal_study_df = source_df %>% 
  mutate(
    load = map(source_df %>% pull(path), read_file)
  ) %>% 
  select(file, load) %>% 
  unnest(cols = load) %>% 
  pivot_longer(
    week_1:week_8, 
    names_to = "week",
    names_prefix = "week_", 
    values_to = "values"
  ) %>% 
  separate(file, into = c("arm", "observation"), sep = "_" ) %>% 
  mutate(
    observation = str_replace(observation, "\\.csv", "")
  )
 

study_plot = longitudinal_study_df %>% 
  group_by(observation) %>% 
  ggplot(aes(x = week, y = values, color = arm, group = arm)) + 
  geom_path()
```


